name: Enhancement
description: "Request new functionality"
labels: ["enhancement"]
body:
  - type: dropdown
    id: STOLMember
    attributes:
      label: "**Employee Status** (Select one)"
      description: "Are you a Saxton Lab/Leidos employee?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: input
    id: organization
    attributes:
      label: Organization Name
      description: "External users only: What organization are you from?"
    validations:
      required: true

  - type: textarea
    id: deployment
    attributes:
      label: How Are You Using or Deploying This Tool?
      description: "External users only: Describe your setup or use case."
      placeholder: e.g. running on-prem, cloud deployment, research use, etc.
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: "External users only: City/State or Country."
    validations:
      required: false

  - type: textarea
    id: external-context
    attributes:
      label: Additional Context for Support
      description: "External users only: Anything else that would help us triage your issue?"
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "Provide a detailed description of the suggested new functionality."
      placeholder: "Be sure to include contextual info, as readers may not be aware of what you are doing."
    validations:
      required: true

  - type: textarea
    id: reasoning
    attributes:
      label: "Reasoning for new functionality"
    validations:
      required: false
