name: Released Bug
description: Report a bug found in a release
labels: ["anomaly", "bug", "released"]
body:
  - type: dropdown
    id: STOLMember
    attributes:
      label: "**Employee Status** (Select one)"
      description: "Are you a Saxton Lab/Leidos employee?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: input
    id: organization
    attributes:
      label: Organization Name
      description: "External users only: What organization are you from?"
    validations:
      required: false

  - type: textarea
    id: deployment
    attributes:
      label: How Are You Using or Deploying This Tool?
      description: "External users only: Describe your setup or use case."
      placeholder: e.g. running on-prem, cloud deployment, research use, etc.
    validations:
      required: false

  - type: input
    id: location
    attributes:
      label: Location
      description: "External users only: City/State or Country."
    validations:
      required: false

  - type: textarea
    id: external-context
    attributes:
      label: Additional Context for Support
      description: "External users only: Anything else that would help us triage your issue?"
    validations:
      required: false

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a detailed description of the problem.
      placeholder: Be sure to include contextual info, as readers may not be aware of what you are doing.
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version are you running that you noticed this problem?
      options:
        - 4.12.0 (Current)
        - 4.11.0 
        - 4.10.0
        - 4.9.0
        - 4.8.0
        - 4.7.1
        - 4.7.0
        - 4.6.1
        - 4.6.0
        - 4.5.1
        - 4.5.0
        - 4.4.3
        - 4.4.2
        - 4.4.1
        - 4.4.0
        - 4.3.0
        - 4.2.0
        - 4.1.0
        - 4.0.3
        - 4.0.0
        - 3.11.0
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what happens in the version noted above that you'd like to change.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce the Actual Behavior
      placeholder: |
        1. Do this
        2. Do that
    validations:
      required: true

  - type: input
    id: related
    attributes:
      label: Related Work
      description: Links to related tickets or prior related work here.
    validations:
      required: false
