name: Unreleased Bug
description: Report a bug not yet in a release
labels: ["anomaly", "bug", "unreleased"]
body:
  - type: dropdown
    id: STOLMember
    attributes:
      label: "**Employee Status** (Select one)"
      description: "Are you a Saxton Lab/Leidos employee?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a detailed description of the problem.
      placeholder: Be sure to include contextual info, as readers may not be aware of what you are doing.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Commit
      description: What commit are you running that you noticed this problem?
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what happens in the commit noted above that you'd like to change.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce the Actual Behavior
      placeholder: |
        1. Do this
        2. Do that
    validations:
      required: true
  - type: input
    id: related
    attributes:
      label: Related Work
      description: Links to related tickets or prior related work here.
